import Image from "next/image";
import Hero from "./components/Hero";
import Info from "./components/Info";
import Featured from "./components/Featured";
export const metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
      <Hero/>
      
      <Featured/>
    </main>
  );
}
